server:
  port: 31200
spring:
  application:
    name: server_UserControl
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.106.80.241:3306/server?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456@zxc
    initialSize: 5  #初始建立连接数量
    minIdle: 5  #最小连接数量
    maxActive: 20 #最大连接数量
    maxWait: 10000  #获取连接最大等待时间，毫秒
    testOnBorrow: true #申请连接时检测连接是否有效
    testOnReturn: false #归还连接时检测连接是否有效
    timeBetweenEvictionRunsMillis: 60000 #配置间隔检测连接是否有效的时间（单位是毫秒）
    minEvictableIdleTimeMillis: 300000  #连接在连接池的最小生存时间（毫秒）

pagehelper:
  helper-dialect: mysql

